### ISSUE TITLE
[Bug] Enemy has reverse flinch distance

### ISSUE THREAD

**Issue by RyanBram** [RexGit/Animated-Enemies#2]
Dear, Rexal.
Thanks for creating a great plugin. I am here want to show you some bugs that I found in your script. I'll write them one per topic, so you can track them easily.

In your script enemy will move forward when getting hit by actors. Actually, enemy should move backward if take damage just like the actor.

**Comment by bsides** [comment]
:+1:

**Comment by RexGit** [comment]
Fixed in the latest version of the patch
